### PR TITLE
C++11 std::function callback and const qualifier

### PR DESCRIPTION
**Pull request by geromueller**
This allows lambdas and other member functions to be passed to Search

### CODE REVIEW

**Comment by geromueller** [comment]
Hey! Done. I also added a check for a valid callback function.

**Comment by AlexVonB** [comment]
Thanks! One last thing that occured to me: could you please change the "tests" to use your new signature?

- https://github.com/nushoin/RTree/blob/master/Test.cpp#L45 
- https://github.com/nushoin/RTree/blob/master/MemoryTest.cpp#L116
- https://github.com/nushoin/RTree/blob/master/TestBadData.cpp#L35

(PS: I am in no way associated with this repo, you are not obliged to listen to me 😅)

**Comment by nushoin** [comment]
@geromueller @AlexVonB since I'm not really maintaining this project anymore, would you like to have commit access and take the maintenance upon yourself?

**Comment by AlexVonB** [comment]
@nushoin I'd gladly help 👍

**Comment by nushoin** [comment]
@AlexVonB I added commit access for you and @geromueller , not sure if there are any other permissions that can be granted. Please contact me at oigevald (at the well known google mail service) if you need other permissions etc.

**Comment by AlexVonB** [comment]
I can close issues, delete coments and it looks like I could merge pull requests. Thank you!

**Pull request merged**
